# Some ideas: https://adamj.eu/tech/2019/03/20/how-i-provision-my-macbook-with-ansible/

- name: Welcome
  debug:
    msg: Setup developer mac!

- name: Cron to dump Brewfile
  cron:
    name: Dump Brewfile
    minute: 0
    hour: 22
    job: /usr/local/bin/brew bundle dump --describe --force --verbose --file {{ lookup('env','PROJECT') }}/src/macos/Brewfile 2>&1 >> $HOME/Library/Logs//auto-brew.log

- name: Cron to wipe Maven repo
  cron:
    name: Wipe Maven Repo
    minute: 15
    hour: 22
    job: rm -rf $HOME/.m2/repository/
