# Some ideas: https://adamj.eu/tech/2019/03/20/how-i-provision-my-macbook-with-ansible/

- name: Welcome
  ansible.builtin.debug:
    msg: Setup developer mac!
  become: no

- name: Add PATH for brew cron
  ansible.builtin.cron:
    name: PATH
    env: yes
    job: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin
  become: no

- name: Cron to dump Brewfile
  ansible.builtin.cron:
    name: Dump Brewfile
    minute: 0
    hour: 22
    job: brew bundle dump --describe --force --verbose --file {{ lookup('env','PROJECT') }}/src/macos/Brewfile 2>&1 >> $HOME/Library/Logs//auto-brew.log
  become: no

- name: Cron to wipe Maven repo
  ansible.builtin.cron:
    name: Wipe Maven Repo
    minute: 15
    hour: 22
    day: 1
    job: rm -rf $HOME/.m2/repository/
  become: no
