# Some ideas: https://adamj.eu/tech/2019/03/20/how-i-provision-my-macbook-with-ansible/

- name: Welcome
  debug:
    msg: Setup developer mac!

# 0 11 * * * /usr/local/bin/brew bundle dump --describe --force --verbose --file /Users/sst/src/private/dotfiles/Brewfile 2>&1 >>/tmp/auto-brew.log
- name: Cron to dump Brewfile
  cron:
    name: "Dump Brewfile"
    minute: 0
    hour: 11
    job: /usr/local/bin/brew bundle dump --describe --force --verbose --file {{ lookup('env','PROJECT') }}/src/macos/Brewfile 2>&1 >> $HOME/Library/Logs//auto-brew.log
